# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
y = y.reshape(len(y),1)

## Encoding categorical data

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])
X[:, 4] = le.fit_transform(X[:, 4])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 0.0 ... 27.9 0 1]
 [0.0 0.0 1.0 ... 33.77 1 0]
 [0.0 0.0 1.0 ... 33.0 3 0]
 ...
 [0.0 0.0 1.0 ... 36.85 0 0]
 [0.0 0.0 0.0 ... 25.8 0 0]
 [0.0 1.0 0.0 ... 29.07 0 1]]


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

## Training the SVR model on the Training set

In [7]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Test set results

In [8]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[10896.96  9724.53]
 [ 9524.93  8547.69]
 [47362.77 45702.02]
 [13670.9  12950.07]
 [11268.14  9644.25]
 [ 5014.06  4500.34]
 [ 3322.2   2198.19]
 [12606.83 11436.74]
 [ 8480.38  7537.16]
 [ 6398.07  5425.02]
 [ 8357.88  6753.04]
 [11595.07 10493.95]
 [ 8452.83  7337.75]
 [ 5287.92  4185.1 ]
 [22049.35 18310.74]
 [12061.44 10702.64]
 [13454.23 12523.6 ]
 [ 4638.55  3490.55]
 [ 7552.08  6457.84]
 [25546.84 33475.82]
 [23810.43 23967.38]
 [13817.47 12643.38]
 [11387.17 23045.57]
 [27783.   23065.42]
 [ 2744.04  1674.63]
 [ 5988.94  4667.61]
 [ 5107.6   3732.63]
 [ 8898.42  7682.67]
 [ 4764.53  3756.62]
 [ 9652.9   8413.46]
 [ 8960.92  8059.68]
 [49171.25 48970.25]
 [13979.42 12979.36]
 [11414.25 20630.28]
 [14713.4  14571.89]
 [ 5265.39  4137.52]
 [ 9446.45  8347.16]
 [40244.38 51194.56]
 [39225.05 40003.33]
 [ 3029.13  1880.49]
 [ 6722.84  5458.05]
 [ 3692.06  2867.12]
 [24062.89 20149.32]
 [46152.95 47496.49]
 [33740.13 36149.48]
 [ 4799.92 26018.95]
 [12044.41 19749.38]
 [ 8019.92  6

## Evaluating the Model Performance

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8869426522677151